name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.APP_JAVA_VERSION }}
      - uses: actions/cache@v2.1.6
        name: Restore gradle cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ env.cache-name }}-
            ${{ runner.OS }}-gradle-
            ${{ runner.OS }}-
      - uses: actions/cache@v2.1.6
        name: Cache gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Check project
        run: ./gradlew check
        env:
          GITHUB_USER: RakSrinaNa
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dropbox:
    runs-on: ubuntu-latest
    needs: build
    if:
      contains('
      refs/heads/master
      ', github.ref)
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.APP_JAVA_VERSION }}
      - uses: actions/cache@v2.1.6
        name: Restore gradle cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ env.cache-name }}-
            ${{ runner.OS }}-gradle-
            ${{ runner.OS }}-
      - uses: actions/cache@v2.1.6
        name: Cache gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Build app
        run: ./gradlew build
        env:
          GITHUB_USER: RakSrinaNa
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy on Dropbox
        uses: deka0106/upload-to-dropbox@v2.0.1
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_DEPLOY_TOKEN }}
          src: "build/libs/youtubestatistics-shaded.jar"
          dest: "/Documents/JARs/YouTubeStatistics.jar"
          mode: overwrite
